"""Generate scripts/003_create_analysis_schema.sql from the canonical seed data.

Regenerate after editing backend/app/seed_data.py:
    python -m backend.scripts.generate_sql_migration
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from backend.app import seed_data


def esc(val: Any) -> str:
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, list):
        # PostgreSQL text[] literal
        parts = [str(v).replace("'", "''") for v in val]
        inner = ",".join(parts)
        return f"ARRAY[{','.join(repr(p).replace(chr(34), chr(39)) for p in parts)}]" if parts else "ARRAY[]::text[]"
    s = str(val).replace("'", "''")
    return f"'{s}'"


def array_lit(values: list[str]) -> str:
    if not values:
        return "ARRAY[]::text[]"
    escaped = [v.replace("'", "''") for v in values]
    return "ARRAY[" + ", ".join(f"'{v}'" for v in escaped) + "]"


SCHEMA = """\
-- ============================================================================
-- Codex Market Analysis Platform — Schema v3
-- Drops the legacy scraper schema and creates the analytical schema seeded
-- with the canonical Claude-provided dataset (source of truth:
-- backend/app/seed_data.py — DO NOT edit this file by hand).
-- ============================================================================

-- Drop legacy tables (user: "drop old data, start new")
DROP TABLE IF EXISTS scrape_logs CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS sources CASCADE;

-- Drop new-schema tables if re-running
DROP TABLE IF EXISTS category_timeseries CASCADE;
DROP TABLE IF EXISTS issue_timeseries CASCADE;
DROP TABLE IF EXISTS competitive_data CASCADE;
DROP TABLE IF EXISTS segment_impact CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS root_causes CASCADE;
DROP TABLE IF EXISTS user_segments CASCADE;
DROP TABLE IF EXISTS issue_categories CASCADE;

-- ---------------------------------------------------------------------------
-- Core tables
-- ---------------------------------------------------------------------------

CREATE TABLE issue_categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#6b7280',
  tier INTEGER NOT NULL CHECK (tier BETWEEN 1 AND 3),
  share_pct NUMERIC(5,2) NOT NULL DEFAULT 0,
  users_affected_pct NUMERIC(5,2) NOT NULL DEFAULT 0,
  summary TEXT,
  cascades_to TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
  action TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_categories_tier ON issue_categories(tier);

CREATE TABLE user_segments (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  developer_count_range TEXT,
  crisis_severity_percentage NUMERIC(5,2) NOT NULL,
  cost_impact_percentage NUMERIC(5,2) NOT NULL,
  recovery_speed_percentage NUMERIC(5,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE root_causes (
  id TEXT PRIMARY KEY,
  product TEXT NOT NULL DEFAULT 'codex',
  title TEXT NOT NULL,
  description TEXT,
  component TEXT,
  error_type TEXT,
  severity TEXT NOT NULL CHECK (severity IN ('critical','high','medium','low')),
  first_detected DATE,
  identified_date DATE,
  fixed_date DATE,
  fixed_in_version TEXT,
  estimated_users_impacted_percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE competitive_data (
  id TEXT PRIMARY KEY,
  product TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  code_quality_score NUMERIC(5,2) NOT NULL,
  efficiency_score NUMERIC(5,2) NOT NULL,
  cost_per_task_usd NUMERIC(8,2) NOT NULL,
  context_window_tokens INTEGER NOT NULL,
  agent_autonomy_score NUMERIC(5,2) NOT NULL,
  market_sentiment NUMERIC(4,3) NOT NULL,
  adoption_rate NUMERIC(5,2) NOT NULL,
  enterprise_readiness_score NUMERIC(5,2) NOT NULL,
  summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE issues (
  id TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  source_id TEXT UNIQUE NOT NULL,
  product TEXT NOT NULL DEFAULT 'codex',
  title TEXT NOT NULL,
  description TEXT,
  url TEXT,
  category_id TEXT REFERENCES issue_categories(id) ON DELETE SET NULL,
  severity TEXT NOT NULL CHECK (severity IN ('critical','high','medium','low')),
  sentiment_score NUMERIC(4,3) NOT NULL,
  engagement_score NUMERIC(6,2) NOT NULL DEFAULT 0,
  mention_count INTEGER NOT NULL DEFAULT 1,
  affected_segments TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
  root_cause_id TEXT REFERENCES root_causes(id) ON DELETE SET NULL,
  duplicate_of_id TEXT REFERENCES issues(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_issues_category ON issues(category_id);
CREATE INDEX idx_issues_root_cause ON issues(root_cause_id);
CREATE INDEX idx_issues_severity ON issues(severity);
CREATE INDEX idx_issues_sentiment ON issues(sentiment_score);
CREATE INDEX idx_issues_created_at ON issues(created_at DESC);
CREATE INDEX idx_issues_affected_segments ON issues USING GIN (affected_segments);

CREATE TABLE issue_timeseries (
  month DATE PRIMARY KEY,
  sentiment NUMERIC(5,2) NOT NULL,
  issue_freq INTEGER NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('baseline','emerging','crisis','peak_crisis','recovery','recovered')),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_timeseries_status ON issue_timeseries(status);

CREATE TABLE category_timeseries (
  category_id TEXT NOT NULL REFERENCES issue_categories(id) ON DELETE CASCADE,
  month DATE NOT NULL,
  issue_count INTEGER NOT NULL,
  sentiment NUMERIC(5,2) NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('baseline','emerging','crisis','peak_crisis','recovery','recovered')),
  PRIMARY KEY (category_id, month)
);

CREATE INDEX idx_category_timeseries_month ON category_timeseries(month);

CREATE TABLE segment_impact (
  id SERIAL PRIMARY KEY,
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  segment_slug TEXT NOT NULL REFERENCES user_segments(slug) ON DELETE CASCADE,
  UNIQUE(issue_id, segment_slug)
);
CREATE INDEX idx_segment_impact_segment ON segment_impact(segment_slug);

-- ---------------------------------------------------------------------------
-- Row-level security (mirrors scripts/002)
-- ---------------------------------------------------------------------------
ALTER TABLE issue_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE root_causes ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitive_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE issue_timeseries ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_timeseries ENABLE ROW LEVEL SECURITY;
ALTER TABLE segment_impact ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read_categories ON issue_categories FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY public_read_segments ON user_segments FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY public_read_root_causes ON root_causes FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY public_read_competitive ON competitive_data FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY public_read_issues ON issues FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY public_read_timeseries ON issue_timeseries FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY public_read_category_timeseries ON category_timeseries FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY public_read_segment_impact ON segment_impact FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY service_write_categories ON issue_categories FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_write_segments ON user_segments FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_write_root_causes ON root_causes FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_write_competitive ON competitive_data FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_write_issues ON issues FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_write_timeseries ON issue_timeseries FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_write_category_timeseries ON category_timeseries FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_write_segment_impact ON segment_impact FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- Seed data
-- ---------------------------------------------------------------------------
"""


def gen_categories() -> str:
    rows = []
    for c in seed_data.CATEGORIES:
        rows.append(
            f"  ({esc(c['id'])}, {esc(c['name'])}, {esc(c['slug'])}, {esc(c['color'])}, "
            f"{c['tier']}, {c['share_pct']}, {c['users_affected_pct']}, "
            f"{esc(c.get('summary'))}, {array_lit(c.get('cascades_to', []))}, "
            f"{esc(c.get('action'))})"
        )
    return (
        "INSERT INTO issue_categories (id, name, slug, color, tier, share_pct, "
        "users_affected_pct, summary, cascades_to, action) VALUES\n"
        + ",\n".join(rows)
        + ";\n\n"
    )


def gen_category_timeseries() -> str:
    rows = []
    for t in seed_data.CATEGORY_TIMESERIES:
        rows.append(
            f"  ({esc(t['category_id'])}, {esc(t['month'])}::date, {t['issue_count']}, "
            f"{t['sentiment']}, {esc(t['status'])})"
        )
    return (
        "INSERT INTO category_timeseries (category_id, month, issue_count, sentiment, status) VALUES\n"
        + ",\n".join(rows)
        + ";\n\n"
    )


def gen_segments() -> str:
    rows = []
    for s in seed_data.USER_SEGMENTS:
        rows.append(
            f"  ({esc(s['id'])}, {esc(s['name'])}, {esc(s['slug'])}, {esc(s['description'])}, "
            f"{esc(s['developer_count_range'])}, {s['crisis_severity_percentage']}, "
            f"{s['cost_impact_percentage']}, {s['recovery_speed_percentage']})"
        )
    return (
        "INSERT INTO user_segments (id, name, slug, description, developer_count_range, "
        "crisis_severity_percentage, cost_impact_percentage, recovery_speed_percentage) VALUES\n"
        + ",\n".join(rows)
        + ";\n\n"
    )


def gen_root_causes() -> str:
    rows = []
    for r in seed_data.ROOT_CAUSES:
        rows.append(
            f"  ({esc(r['id'])}, 'codex', {esc(r['title'])}, {esc(r['description'])}, "
            f"{esc(r['component'])}, {esc(r['error_type'])}, {esc(r['severity'])}, "
            f"{esc(r['first_detected'])}::date, {esc(r['identified_date'])}::date, "
            f"{esc(r['fixed_date'])}::date, {esc(r['fixed_in_version'])}, "
            f"{r['estimated_users_impacted_percentage']})"
        )
    return (
        "INSERT INTO root_causes (id, product, title, description, component, error_type, severity, "
        "first_detected, identified_date, fixed_date, fixed_in_version, "
        "estimated_users_impacted_percentage) VALUES\n"
        + ",\n".join(rows)
        + ";\n\n"
    )


def gen_competitive() -> str:
    rows = []
    for c in seed_data.COMPETITIVE_DATA:
        rows.append(
            f"  ({esc(c['id'])}, {esc(c['product'])}, {esc(c['display_name'])}, "
            f"{c['code_quality_score']}, {c['efficiency_score']}, {c['cost_per_task_usd']}, "
            f"{c['context_window_tokens']}, {c['agent_autonomy_score']}, {c['market_sentiment']}, "
            f"{c['adoption_rate']}, {c['enterprise_readiness_score']}, {esc(c['summary'])})"
        )
    return (
        "INSERT INTO competitive_data (id, product, display_name, code_quality_score, efficiency_score, "
        "cost_per_task_usd, context_window_tokens, agent_autonomy_score, market_sentiment, "
        "adoption_rate, enterprise_readiness_score, summary) VALUES\n"
        + ",\n".join(rows)
        + ";\n\n"
    )


def gen_issues() -> str:
    rows = []
    impact_rows: list[str] = []
    for i in seed_data.ISSUES:
        rows.append(
            f"  ({esc(i['id'])}, {esc(i['source'])}, {esc(i['source_id'])}, 'codex', "
            f"{esc(i['title'])}, {esc(i['description'])}, {esc(i['url'])}, "
            f"{esc(i['category_id'])}, {esc(i['severity'])}, {i['sentiment_score']}, "
            f"{i['engagement_score']}, {i['mention_count']}, "
            f"{array_lit(i['affected_segments'])}, {esc(i['root_cause_id'])}, "
            f"{esc(i['created_at'])}::timestamptz)"
        )
        for seg in i["affected_segments"]:
            impact_rows.append(f"  ({esc(i['id'])}, {esc(seg)})")
    sql = (
        "INSERT INTO issues (id, source, source_id, product, title, description, url, "
        "category_id, severity, sentiment_score, engagement_score, mention_count, "
        "affected_segments, root_cause_id, created_at) VALUES\n"
        + ",\n".join(rows)
        + ";\n\n"
    )
    if impact_rows:
        sql += (
            "INSERT INTO segment_impact (issue_id, segment_slug) VALUES\n"
            + ",\n".join(impact_rows)
            + ";\n\n"
        )
    return sql


def gen_timeline() -> str:
    rows = []
    for t in seed_data.TIMELINE:
        rows.append(
            f"  ({esc(t['month'])}::date, {t['sentiment']}, {t['issue_freq']}, "
            f"{esc(t['status'])}, {esc(t['note'])})"
        )
    return (
        "INSERT INTO issue_timeseries (month, sentiment, issue_freq, status, note) VALUES\n"
        + ",\n".join(rows)
        + ";\n"
    )


def main() -> None:
    out = (
        SCHEMA
        + gen_categories()
        + gen_segments()
        + gen_root_causes()
        + gen_competitive()
        + gen_issues()
        + gen_timeline()
        + gen_category_timeseries()
    )
    path = Path(__file__).resolve().parents[2] / "scripts" / "003_create_analysis_schema.sql"
    path.write_text(out)
    print(f"wrote {path} ({len(out.splitlines())} lines)")


if __name__ == "__main__":
    main()
